spring:
  application:
    name: socialapp
  servlet:
    multipart:
      file-size-threshold: 10MB
      location: ${SBIP_SPRING_SERVLET_MULTIPART_LOCATION:/tmp}
      max-file-size: 100MB
      max-request-size: 100MB
  datasource:
    url: ${SBIP_SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/socialapp?serverTimezone=UTC&useSSL=false}
    username: ${SBIP_SPRING_DATASOURCE_USERNAME:root}
    password: ${SBIP_SPRING_DATASOURCE_PASSWORD:80771696abCD}
  flyway:
    enabled: true
    locations: classpath:db/migration/{vendor}
    clean-disabled: true
    baseline-on-migrate: true